### ISSUE TITLE
[SOLVED] Middleware six/attribute error

### ISSUE THREAD

**Issue by golightlyb** [falconry/falcon#1011]
Installed falcon through pip(3) today, and tried to use a simple Middleware example from the Quickstart, with error.

**error.py:**

```
import falcon

class TestMiddleware(object):
    def process_request(self, req, resp):
        pass

app = falcon.API(middleware=[TestMiddleware])
```

**Running `python3 ./error.py` gives.**

```
Traceback (most recent call last):
  File "./error.py", line 7, in <module>
    app = falcon.API(middleware=[TestMiddleware])
  File "/usr/local/lib/python3.4/dist-packages/falcon/api.py", line 133, in __init__
    self._middleware = helpers.prepare_middleware(middleware)
  File "/usr/local/lib/python3.4/dist-packages/falcon/api_helpers.py", line 44, in prepare_middleware
    'process_request')
  File "/usr/local/lib/python3.4/dist-packages/falcon/util/misc.py", line 243, in get_bound_method
    if six.get_method_self(method) is None:
AttributeError: 'function' object has no attribute '__self__'
```

**Versions**

```
pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)
python3 --version
Python 3.4.2
```

Many thanks for any help

**Comment by golightlyb** [comment]
import falcon

class TestMiddleware(object):
    def process_request(self, req, resp):
        pass

app = falcon.API(middleware=[TestMiddleware()])

Sorry - just realised. Didn't instantiate the class. Should be TestMiddleware**(),** not TestMiddleware.

Please mark as closed!
