### ISSUE TITLE
ImportError: cannot import name UserDict

### ISSUE THREAD

**Issue by slavaspirit** [falconry/falcon#1139]
Just install Falcon and tried to launch examples. And got an error right from the start:

`
[2017-11-26 12:26:59 +0300] [1362] [INFO] Starting gunicorn 19.7.1
[2017-11-26 12:26:59 +0300] [1362] [INFO] Listening at: http://127.0.0.1:8000 (1362)
[2017-11-26 12:26:59 +0300] [1362] [INFO] Using worker: sync
[2017-11-26 12:26:59 +0300] [1365] [INFO] Booting worker with pid: 1365
[2017-11-26 12:26:59 +0300] [1365] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Library/Python/2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Library/Python/2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Library/Python/2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Python/2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Library/Python/2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Python/2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/sergeev/Public/things.py", line 4, in <module>
    import falcon
  File "/Library/Python/2.7/site-packages/falcon/__init__.py", line 30, in <module>
    from falcon.api import API  # NOQA
  File "falcon/api.py", line 21, in init falcon.api
    from falcon import api_helpers as helpers, DEFAULT_MEDIA_TYPE, routing
  File "/Library/Python/2.7/site-packages/falcon/routing/__init__.py", line 22, in <module>
    from falcon.routing.compiled import CompiledRouter, CompiledRouterOptions  # NOQA
  File "falcon/routing/compiled.py", line 21, in init falcon.routing.compiled
    from six.moves import UserDict
ImportError: cannot import name UserDict
[2017-11-26 12:26:59 +0300] [1365] [INFO] Worker exiting (pid: 1365)
[2017-11-26 12:26:59 +0300] [1362] [INFO] Shutting down: Master
[2017-11-26 12:26:59 +0300] [1362] [INFO] Reason: Worker failed to boot.
`

What am I need to do with that? Just tried to launch copy-pasted code from example with `gunicorn things:app` :

`
import falcon

class ThingsResource(object):
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200  # This is the default status
        resp.body = ('\nTwo things awe me most, the starry sky '
                     'above me and the moral law within me.\n'
                     '\n'
                     '    ~ Immanuel Kant\n\n')

app = falcon.API()

things = ThingsResource()

app.add_route('/things', things)
`

**Comment by kgriffs** [comment]
Hmm, that may be caused by having an outdated version of six that was already installed before installing falcon. You might try running `pip install --upgrade six`.

**Comment by slavaspirit** [comment]
Kgriffs, thx for respond. I found, that I used different Python versions. My main system Python version is 2, but I’m installed Falcon with pip3. When I created new virtual environment with Python 3 and install falcon under it, all works like a charm.

**Comment by iron2414** [comment]
I have the same issue. I have a fresh ubuntu install and i installed the following things:
apt install python-pip
apt install python3-pip
pip3 install gunicorn
pip3 install falcon
And i modified the usr/local/bin/gunicorn file header to "#!/usr/bin/python3" so it will start my application in python3.
When i run gunicorn -c gunicorn_conf.py --reload test:app
i get the same error message. What am i doing wrong?
