### ISSUE TITLE
KeyError: 'wsgi.errors'

### ISSUE THREAD

**Issue by totaki** [falconry/falcon#1209]
I try use https://unit.nginx.org/.

I get error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 194, in __call__
    req = self._request_type(env, options=self.req_options)
  File "/usr/local/lib/python3.5/dist-packages/falcon/request.py", line 421, in __init__
    self._wsgierrors = env['wsgi.errors']
KeyError: 'wsgi.errors'
```

**Comment by vytas7** [comment]
The below is not to say that your report is invalid, and yes, I agree it would be cool getting Falcon to run on Nginx Unit, but IMHO one shall point out that ``wsgi.errors`` variable in mandated by the WSGI specification -- https://www.python.org/dev/peps/pep-0333/#environ-variables reads:

> In addition to the CGI-defined variables, the environ dictionary **may** also contain arbitrary operating-system "environment variables", and **must** contain the following WSGI-defined variables

**Comment by kgriffs** [comment]
Indeed, this is an Nginx Unit bug since it does not conform to the spec. I've reported the issue.
