### ISSUE TITLE
Examples Web Page needs Updating

### ISSUE THREAD

**Issue by stevecw** [falconry/falcon#1635]
On this [web page](https://falcon.readthedocs.io/en/stable/user/quickstart.html#more-features), Line 122 of the example code needs to be changed to:
`def process_response(self, req, resp, resource, req_succeeded):`
_(Added **req_succeeded** parameter)_

Without the parameter gunicorn crashes with this error
```
[2020-01-08 13:21:35 -0800] [37808] [ERROR] Error handling request /things
Traceback (most recent call last):
  File "/Users/someone/Sites/look/.venv/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/someone/Sites/look/.venv/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/someone/Sites/look/.venv/lib/python3.8/site-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 4 positional arguments but 5 were given
```

I found the solution to the crash, via StackOverflow, in [issue #1534](https://github.com/falconry/falcon/issues/1534)

**Comment by kgriffs** [comment]
Thanks for the report! This has been fixed for the impending 3.0.0 release.
