### ISSUE TITLE
Custom error handler that won't raise the exception in the CLI

### ISSUE THREAD

**Issue by Seluj78** [falconry/falcon#1898]
Hi,

I'm looking into custom error handling for my API and I cannot seem to get custom error handling as I'd wish, unlike on flask. 

On Flask, I can do custom error handlers that would look like this https://github.com/Seluj78/PyMatcha/blob/dev/backend/PyMatcha/utils/errors/badrequest.py and will simply return a custom message and code.

Whereas on Falcon, whenever there's a for example 404 raised, it is also raised in the CLI.

Is there anyway to have a better custom exception experience ?

**Comment by vytas7** [comment]
Hi @Seluj78 !
I believe Falcon features comparable error handling mechanisms.

There are different ways you can customize error handling in Falcon:
* Define and raise custom subclasses of [HTTPError](https://falcon.readthedocs.io/en/latest/api/errors.html#falcon.HTTPError) and [HTTPStatus](https://falcon.readthedocs.io/en/latest/api/status.html#falcon.HTTPStatus).
* [Add error handler](https://falcon.readthedocs.io/en/latest/api/app.html#falcon.App.add_error_handler)s for custom exception classes. You handle can also choose to raise an instance of [HTTPError](https://falcon.readthedocs.io/en/latest/api/errors.html#falcon.HTTPError) or [HTTPStatus](https://falcon.readthedocs.io/en/latest/api/status.html#falcon.HTTPStatus).
* Customize error serialization via [`set_error_serializer()`](https://falcon.readthedocs.io/en/latest/api/app.html#falcon.App.set_error_serializer). In other words, you can customize how instances of  [HTTPError](https://falcon.readthedocs.io/en/latest/api/errors.html#falcon.HTTPError) or [HTTPStatus](https://falcon.readthedocs.io/en/latest/api/status.html#falcon.HTTPStatus) are converted into error responses.

The upcoming Falcon 3.0 (pending imminent stable release, the hopefully final release candidate `rc2` is out) changes how exception classes are matched: the error handler is now selected by the most-specific matching error class, rather than the most-recently registered matching error class. I believe this is roughly how your mentioned Flask & Werkzeug work too.
In Falcon 2.0, you might need to take care in which order error handlers are registered (if any of the exception classes are overlapping in the inheritance tree).

Another noteworthy change is that the framework is always installing a default error handler for `Exception` in 3.0. So, even if you don't provide your own, the framework will raise an instance of [HTTPInternalServerError](https://falcon.readthedocs.io/en/latest/api/errors.html#falcon.HTTPInternalServerError) which you can style via [`set_error_serializer()`](https://falcon.readthedocs.io/en/latest/api/app.html#falcon.App.set_error_serializer).

Does this shed any light on the subject, or did you have anything else in mind wrt "better custom exception experience"?

**Comment by vytas7** [comment]
Adding to my answer, see also how `StorageError` is handled here: [A More Complex Example](https://falcon.readthedocs.io/en/latest/user/quickstart.html#a-more-complex-example).

**Comment by Seluj78** [comment]
Thank you for this information !

It looks like the `set_error_serializer` will be able to do what I want ! I'm going to try this out and let you know if I have more questions

My only concern left is the way Falcon raises an error whenever something goes wrong

From what I am used to with Flask, when an error is raised, it being a 404 because I raised it manually or a 500 because something is unhandled, flask will simply handle it the way it knows how, if no error handler is added then it's a 500 returned to the client.

Whereas Falcon, No matter if the error has a handler or not, it will always return a response and also raise the error in the CLI like so :

```python
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/schema.py", line 189, in resolve_asset
    return Resolver.resolve_asset_by_id(info.context, asset_id)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/src/aplines/aplines/utils/auth.py", line 231, in wrap_try
    return func(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/resolvers.py", line 79, in resolve_asset_by_id
    raise DoesNotExist(f"Asset with id {asset_id} does not exist")
graphql.error.located_error.GraphQLLocatedError: Asset with id 6009b004adeeb672a817e9ae does not exist
```

but in the graphql output I get this:

```json
{
  "data": {
    "asset": null
  },
  "errors": [
    {
      "message": "Asset with id 6009b004adeeb672a817e9ae does not exist"
    }
  ]
}
```

I've also checked my company's codebase and we're currently not using `set_error_serializer` so I was wondering if it was a standard behaviour and if there was a way to stop it ?

My goal would be to have this to raise an error

```python
...
raise UnauthorizedError
...
```

In the CLI:

```
AssetService | Juless-MacBook-Pro.local | 1.3.0 | 96991 | 2021-04-06 09:32:39,538  | WARNING  | graphql_resource | 95 | on_post | Query failed, Unauthorized
```

and in the returned values (GraphQL or REST)

```json
{
  "code": "400",
  "success": false,
  "error": {
    "type": "UnauthorizedError",
    "name": "Unauthorized Error",
    "message": "XXX",
    "solution": "XXX"
  }
}

```

**Comment by Seluj78** [comment]
Also it looks like `set_error_serializer` only works for handled HTTPERROR based exceptions and not unhandled exceptions like my `GraphQLLocatedError` shown above. How can I handle those to return a 500 ?

**Comment by Seluj78** [comment]
Yeah even if I change the custom exception to a Falcon one

```
Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/schema.py", line 189, in resolve_asset
    return Resolver.resolve_asset_by_id(info.context, asset_id)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/src/aplines/aplines/utils/auth.py", line 231, in wrap_try
    return func(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/resolvers.py", line 79, in resolve_asset_by_id
    raise falcon.HTTPNotFound(f"Asset with id {asset_id} does not exist")
falcon.errors.HTTPNotFound: Asset with id 6009b004adeeb672a817e9ae does not exist
```

I still get it in the CLI and it isn't modified by my custon serializer

**Comment by vytas7** [comment]
Hi again @Seluj78,
as explained in my previous answer, Falcon 3.0 does render a 500 response for (almost) all otherwise unhandled errors. Falcon 3.0 is now the latest stable release.

As to other issues reported above, we need to dig deeper into those. 

Which Falcon version are you using btw? At a first glance, the behaviour you are reporting for the custom serializer hints of 1.4.1 or older (?)

**Comment by Seluj78** [comment]
```
(AssetGQLService)(py3.8.1rc1) ➜  AssetGQLService git:(map-pagination) ✗ pip freeze | grep falcon  
falcon==2.0.0
```

Here's my Falcon version !

Well I might try and see if we can move to Falcon 3.0 ! Is there any major breaking changes ? (I'm going to read the changelog)

**Comment by Seluj78** [comment]
I noticed a thing missing in your breaking changes

I've upgraded my Falcon version and of course it broke 😉 

```
ModuleNotFoundError: No module named 'falcon.api_helpers'
```

And this change is not writter anywhere in your changelog (The fact that api_helpers doesn't exist anymore)

**Comment by vytas7** [comment]
Ouch, we'll take a look at this 😬 

Which function were you using from the said module? IIRC the last public function was removed as per the breaking change in 2.0, but I may be wrong.

**Comment by Seluj78** [comment]
Alright I've managed to get past the error by deactivating sentry, here's what I get now

```python
Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/schema.py", line 189, in resolve_asset
    return Resolver.resolve_asset_by_id(info.context, asset_id)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/src/aplines/aplines/utils/auth.py", line 231, in wrap_try
    return func(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/resolvers.py", line 79, in resolve_asset_by_id
    raise falcon.HTTPNotFound(f"Asset with id {asset_id} does not exist")
falcon.errors.HTTPNotFound: <HTTPNotFound: 404 Not Found>
AssetService | Juless-MacBook-Pro.local | 1.3.0 | 99634 | 2021-04-06 10:15:14,583  | ERROR    | utils | 155 | report_error | Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/schema.py", line 189, in resolve_asset
    return Resolver.resolve_asset_by_id(info.context, asset_id)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/src/aplines/aplines/utils/auth.py", line 231, in wrap_try
    return func(*args, **kwargs)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/graphql_server/resolvers.py", line 79, in resolve_asset_by_id
    raise falcon.HTTPNotFound(f"Asset with id {asset_id} does not exist")
graphql.error.located_error.GraphQLLocatedError: <HTTPNotFound: 404 Not Found>
```

```json
{
  "data": {
    "asset": null
  },
  "errors": [
    {
      "message": "<HTTPNotFound: 404 Not Found>"
    }
  ]
}
```

**Comment by Seluj78** [comment]
> Ouch, we'll take a look at this 😬
> 
> Which function were you using from the said module? IIRC the last public function was removed as per the breaking change in 2.0, but I may be wrong.

Apparently this was sentry with the falcon integration, like so :

```
/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/bin/python /Users/seluj78/Projects/ApLines/asset-register-service/.venv/bin/gunicorn -b :5001 -t 0 --preload gql_service.app:ASSET_APP
Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/asset-register-service/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/app.py", line 6, in <module>
    from sentry_sdk.integrations.falcon import FalconIntegration
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/falcon.py", line 4, in <module>
    import falcon.api_helpers  # type: ignore
ModuleNotFoundError: No module named 'falcon.api_helpers'
```

With this version of the sentry sdk

```
sentry-sdk[falcon]==0.10.2
```

and Falcon 3.0 (No issues when using Falcon 2)

**Comment by vytas7** [comment]
Right, thanks. We'll need to investigate the breaking change.

**Comment by Seluj78** [comment]
Thanks ! Do know that the version of sentry-sdk we're using dates back from July of 2016. If I upgrade to the lastest sentry version, here's my error:

```sh
(AssetGQLService)(py3.8.1rc1) ➜  AssetGQLService git:(map-pagination) ✗ pip install --upgrade 'sentry-sdk[falcon]'
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: sentry-sdk[falcon] in ./.venv/lib/python3.8/site-packages (0.10.2)
Collecting sentry-sdk[falcon]
  Using cached sentry_sdk-1.0.0-py2.py3-none-any.whl (131 kB)
Requirement already satisfied: urllib3>=1.10.0 in ./.venv/lib/python3.8/site-packages (from sentry-sdk[falcon]) (1.26.4)
Requirement already satisfied: certifi in ./.venv/lib/python3.8/site-packages (from sentry-sdk[falcon]) (2020.12.5)
Requirement already satisfied: falcon>=1.4 in ./.venv/lib/python3.8/site-packages (from sentry-sdk[falcon]) (3.0.0)
Installing collected packages: sentry-sdk
  Attempting uninstall: sentry-sdk
    Found existing installation: sentry-sdk 0.10.2
    Uninstalling sentry-sdk-0.10.2:
      Successfully uninstalled sentry-sdk-0.10.2
Successfully installed sentry-sdk-1.0.0
```

```python
/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/bin/python /Users/seluj78/Projects/ApLines/asset-register-service/.venv/bin/gunicorn -b :5001 -t 0 --preload gql_service.app:ASSET_APP
Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/falcon.py", line 20, in <module>
    import falcon.api_helpers  # type: ignore
ModuleNotFoundError: No module named 'falcon.api_helpers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/seluj78/Projects/ApLines/asset-register-service/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/gql_service/app.py", line 6, in <module>
    from sentry_sdk.integrations.falcon import FalconIntegration
  File "/Users/seluj78/Projects/ApLines/AssetGQLService/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/falcon.py", line 24, in <module>
    raise DidNotEnable("Falcon not installed")
sentry_sdk.integrations.DidNotEnable: Falcon not installed
```

(This error is with Falcon 3.0 and sentry-sdk 1.0)

**Comment by vytas7** [comment]
Which is sort of graceful degradation on their side 🙂 

I see what we did though, we didn't announce that api_helpers was moved to app_helpers

**Comment by Seluj78** [comment]
Ahh that's what I thought ! :) I guess I can make a PR on sentry-sdk then !

Thanks for the reactivity and sorry for spamming you, I'm trying to give you as much info as possible !

We're going to be deciding this afternoon if we switch from 2->3 for Falcon, if we do I'll make sure to let you know if I find anything else that causes problems (Maybe in another issue though, This one was about error handling)

**Comment by vytas7** [comment]
Thanks for reporting this. 

I'm yet to look at the exception propagation issue. Or does Falcon 3.0 work as expected for you in that aspect?

**Comment by Seluj78** [comment]
Nope, still doesn't work as you told me it would tho :/

This is the one with Falcon 3.0

https://github.com/falconry/falcon/issues/1898#issuecomment-813926184

**Comment by vytas7** [comment]
Getting back to the issue at hand.

So it seems that your final response is not rendered directly by the framework, but there is another component doing that, either [Falcon middleware](https://falcon.readthedocs.io/en/stable/api/middleware.html) doing `process_response`, or generic WSGI middleware (?).

Which chooses to represent the error the way it does, and it may also be the said component logging the error to your terminal.

So I'm not sure what Falcon can do about this. Do you know which GraphQL middleware is in use, and how it operates?

**Comment by Seluj78** [comment]
> So I'm not sure what Falcon can do about this. Do you know which GraphQL middleware is in use, and how it operates?

Sadly I am not fully aware of how the whole codebase works so I'll ask my colleagues about it, I'm sure they'll know !

**Comment by vytas7** [comment]
Adding to [my previous response](https://github.com/falconry/falcon/issues/1898#issuecomment-812625822), I have now created a simple example: [Falcon error handling examples](https://gist.github.com/vytas7/068ac5bd8a0fd118052d32e30be67792).

**Comment by vytas7** [comment]
Hi again @Seluj78 , just checking if you have had the opportunity to check the middleware setup with your team?

**Comment by Seluj78** [comment]
Hi!

Sadly I haven't had time to work on this, as the feature priorities shifted sorry. But when I get back on this topic I'll definetly let you know!

**Comment by vytas7** [comment]
Closing this in the absence of further information, but feel free to reopen, drop a comment here, or open a new issue, if you gather more data indicating this is something that needs to be fixed in the framework.
