### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by ChandanChainani** [falconry/falcon#2142]
```
Traceback (most recent call last):
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "$HOME/code/sample/issue.py", line 1, in <module>
    import falcon
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/falcon/__init__.py", line 30, in <module>
    from falcon.api import API  # NOQA
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/falcon/api.py", line 21, in <module>
    from falcon import api_helpers as helpers, DEFAULT_MEDIA_TYPE, routing
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/falcon/api_helpers.py", line 21, in <module>
    from falcon import util
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/falcon/util/__init__.py", line 29, in <module>
    from falcon.util import structures
  File "$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/lib/python3.10/site-packages/falcon/util/structures.py", line 35, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):  # pragma: no cover
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

In python 3.10 and above `MutableMapping` is moved under `from collections.abc import MutableMapping`

**Comment by CaselIT** [comment]
Hi,

what version of falcon are you using?

**Comment by ChandanChainani** [comment]
@CaselIT falcon version `3.1.1`

**Comment by vytas7** [comment]
Hi @ChandanChainani,
this doesn't look like `3.1.1` :confused: 

The way you are importing `api` and `api_helpers` hints that you using no later than `2.0`.

Could you check in the virtualenv in question, for instance
```
$HOME/.local/share/virtualenvs/sample-ljXl0Lhp/bin/pip freeze | grep falcon
```

Thank you.

**Comment by CaselIT** [comment]
Also I'm using python 3.10.9 with falcon 3.1.1 without issues at the moment, so try re-installing falcon in your local env

**Comment by ChandanChainani** [comment]
@vytas7 you are right it is falcon `1.4.1` tried with `3.1.1` it is working closing the issue.

Thanks @vytas7 @CaselIT

**Comment by vytas7** [comment]
No worries, glad you sorted it out! :rocket:
