### ISSUE TITLE
Falcon 3.1.3 installation breaks on python 3.13

### ISSUE THREAD

**Issue by DavideCanton** [falconry/falcon#2376]
Hi, not sure if this bug was already known, but I did not find anything in the issue tracker.

It seems that installing `falcon==3.1.3` in a python 3.13 virtualenv fails with the error `AttributeError: module 'falcon' has no attribute '__version__'`. The `4.0.0rc1` version installs just fine.

Tried on both linux (under wsl) and windows.

<details>
<summary>Full error</summary>

```
$ python3.13 -m pip install "falcon<4"
Defaulting to user installation because normal site-packages is not writeable
Collecting falcon<4
  Using cached falcon-3.1.3.tar.gz (577 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/expand.py", line 69, in __getattr__
          return next(
              ast.literal_eval(value)
              for target, value in self._find_assignments()
              if isinstance(target, ast.Name) and target.id == attr
          )
      StopIteration

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/expand.py", line 183, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/expand.py", line 75, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: falcon has no attribute __version__

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 197, in <module>
        File "<string>", line 174, in run_setup
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
          ~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/dist.py", line 643, in parse_config_files
          setupcfg.parse_configuration(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              self, self.command_options, ignore_option_errors=ignore_option_errors
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 193, in parse_configuration
          meta.parse()
          ~~~~~~~~~~^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 506, in parse
          section_parser_method(section_options)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 481, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 299, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 598, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/setupcfg.py", line 423, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-onbazeod/overlay/local/lib/python3.13/dist-packages/setuptools/config/expand.py", line 187, in read_attr
          return getattr(module, attr_name)
      AttributeError: module 'falcon' has no attribute '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

**Comment by vytas7** [comment]
Hi @DavideCanton!
Thanks for reporting.

This is not a bug per se, [Falcon `3.1.3`](https://pypi.org/project/falcon/3.1.3/) supports only up to Python 3.12. That is why we are trying to get 4.0.0 out ASAP... :cold_sweat:

**Comment by vytas7** [comment]
Duplicates #2066
Duplicates #2258

**Comment by DavideCanton** [comment]
Ah, okay, I missed that piece of information. I searched for some issues in the tracker but I did not read anything explicit regarding dropping support entirely for 3.13.

Guess I'll stick with 4.0.0rc1.

Thanks!

**Comment by vytas7** [comment]
Thanks, don't hesitate to report back any issues you find `4.0.0rc1`!
Barring any serious bugs discovered, the ETA for 4.0.0 stable is around Monday.

**Comment by vytas7** [comment]
Thanks for testing the release candidate, and thank your for your patience @DavideCanton! You can now upgrade to a stable version, [Falcon 4.0.0](https://github.com/falconry/falcon/releases/tag/4.0.0) is out!
