### ISSUE TITLE
Falcon 3.1.3 does not install on Win11 with latest Python v3.13.0

### ISSUE THREAD

**Issue by jdmorriso** [falconry/falcon#2377]
**Description**
The latest release of Python 3.13.0 for Windows 11 breaks the installation of Falcon 3.1.3

**Steps to reproduce.**
1. Download and install Python 3.13.0 from the Python Website. https://www.python.org/downloads/
2. Enter the command `pip install falcon`, and the following error message appears.

**Expected behavior.**
No error message on installation.
Falcon installs correctly on Python 3.12.7

**Error message**
PS C:\Users\David\Documents\alpaca-benro-polaris-main> python --version
Python 3.13.0
PS C:\Users\David\Documents\alpaca-benro-polaris-main> pip install falcon
Collecting falcon
  Using cached falcon-3.1.3.tar.gz (577 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      Traceback (most recent call last):
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\expand.py", line 69, in __getattr__
          return next(
              ast.literal_eval(value)
              for target, value in self._find_assignments()
              if isinstance(target, ast.Name) and target.id == attr
          )
      StopIteration

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\expand.py", line 183, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\expand.py", line 75, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: falcon has no attribute __version__

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\David\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\David\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\David\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 197, in <module>
        File "<string>", line 174, in run_setup
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 157, in setup
          dist.parse_config_files()
          ~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\dist.py", line 643, in parse_config_files
          setupcfg.parse_configuration(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              self, self.command_options, ignore_option_errors=ignore_option_errors
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 193, in parse_configuration
          meta.parse()
          ~~~~~~~~~~^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 506, in parse
          section_parser_method(section_options)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 481, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 299, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 598, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 423, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\David\AppData\Local\Temp\pip-build-env-_80t8vlv\overlay\Lib\site-packages\setuptools\config\expand.py", line 187, in read_attr
          return getattr(module, attr_name)
      AttributeError: module 'falcon' has no attribute '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by vytas7** [comment]
Hi @jdmorriso!
And thanks for reporting this. The limitation is known, Falcon 3.1.3 supports Python versions 3.5 through 3.12.

Our apologies we're a couple of days late with the upcoming 4.0.0 release that does support Python 3.13.
A release candidate is available: [Falcon `4.0.0rc1`](https://pypi.org/project/falcon/4.0.0rc1/).

Could you test the release candidate with your projects, and report back to us in case you run into any issues? Thanks!
You can see the list of changes here: https://falcon.readthedocs.io/en/latest/changes/4.0.0.html.

**Comment by CaselIT** [comment]
Hi,
As mentioned v4 will fix.

Duplicates #2066
Duplicates #2258
Duplicates #2376

**Comment by jdmorriso** [comment]
Thanks @vytas7, 
I've confirmed Falcon 4.0.0rc1 resolves the issue and passes all tests for the application. Sorry for the duplicate.
Dave

**Comment by vytas7** [comment]
Thanks for testing the release candidate, and thank your for your patience @jdmorriso! You can now upgrade to a stable version, [Falcon 4.0.0](https://github.com/falconry/falcon/releases/tag/4.0.0) is out!
