### ISSUE TITLE
Error using Raven WSGI Middleware

### ISSUE THREAD

**Issue by neilalbrock** [falconry/falcon#266]
I am attempting to use the Raven WSGI Middleware in order to log errors to Sentry, as per [the docs](http://raven.readthedocs.org/en/latest/config/wsgi.html).

However after doing this and introducing an artificial error into a Resource, I see the error logged as expected in Sentry but the following is thrown by the wsgiref server. This then results in the client receiving no content, rather than the usual 500 response.

```
12:11:17 web.1     | Traceback (most recent call last):
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 86, in run
12:11:17 web.1     |     self.finish_response()
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 131, in finish_response
12:11:17 web.1     |     self.close()
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 33, in close
12:11:17 web.1     |     self.status.split(' ',1)[0], self.bytes_sent
12:11:17 web.1     | AttributeError: 'NoneType' object has no attribute 'split'
12:11:17 web.1     | 127.0.0.1 - - [08/May/2014 12:11:17] "GET /v1/nodes/2258311 HTTP/1.1" 500 59
12:11:17 web.1     | ----------------------------------------
12:11:17 web.1     | Exception happened during processing of request from ('127.0.0.1', 51394)
12:11:17 web.1     | Traceback (most recent call last):
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
12:11:17 web.1     |     self.process_request(request, client_address)
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
12:11:17 web.1     |     self.finish_request(request, client_address)
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
12:11:17 web.1     |     self.RequestHandlerClass(request, client_address, self)
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 649, in __init__
12:11:17 web.1     |     self.handle()
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 124, in handle
12:11:17 web.1     |     handler.run(self.server.get_app())
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 92, in run
12:11:17 web.1     |     self.close()
12:11:17 web.1     |   File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 33, in close
12:11:17 web.1     |     self.status.split(' ',1)[0], self.bytes_sent
12:11:17 web.1     | AttributeError: 'NoneType' object has no attribute 'split'
12:11:17 web.1     | ----------------------------------------
```

Not really sure where I've gone wrong, or if this is a bug with Falcon itself. Any help would be much appreciated.

**Comment by muodov** [comment]
@neilalbrock how exactly did you ensure that status is correct? I am trying to get raven report unhandled exceptions in the app, but I get the same error.

**Comment by ysegorov** [comment]
@muodov I'm a bit late probably
here is a code snippet I'm using to send errors to self-hosted sentry
have no idea if it's the right way of handling unknown errors, but it works :)
and I'm still experimenting - `falcon` noob here
```python
import falcon
from raven import Client
from svc import conf

app = falcon.API()

if conf.sentry_dsn:
    client = Client(conf.sentry_dsn)

    def internal_error_handler(ex, req, resp, params):
        data = {
            'request': {
                'url': req.url,
                'method': req.method,
                'query_string': req.query_string,
                'env': req.env,
                'data': req.params,
                'headers': req.headers,
            }
        }
        message = isinstance(ex, falcon.HTTPError) and ex.title or str(ex)
        ident = client.captureException(message=message, data=data)

        if not isinstance(ex, falcon.HTTPError):
            resp.status = falcon.HTTP_500
            resp.body = ('A server error occurred (reference code: "%s"). '
                         'Please contact the administrator.' % ident)
        else:
            raise ex

    app.add_error_handler(Exception, internal_error_handler)
```
hope it will be useful for someone searching for `sentry` integration
