### ISSUE TITLE
Add support for Jython

### ISSUE THREAD

**Issue by jimbaker** [falconry/falcon#458]
Installed and tested directly with nose (tox doesn't yet support Jython due to missing virtualenv support). I built from trunk (hg.python.org/jython), but you should be able to replicate with the recent beta 4 (http://www.jython.org/). Use jython -m ensurepip to bootstrap, then install using bin/pip, bin/nosetests as usual.

```
======================================================================
ERROR: Failure: ImportError (No module named multiprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/loader.py", line 413, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/jbaker/opensource/falcon/tests/test_request_body.py", line 2, in <module>
    import multiprocessing
ImportError: No module named multiprocessing
```
No multiprocessing module on Jython, use threading module instead.

```
======================================================================
ERROR: Failure: SyntaxError (Unknown encoding: utf-8- (test_utils.py, line 1))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/loader.py", line 413, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/jbaker/opensource/falcon/tests/test_utils.py", line 1

   ^
SyntaxError: Unknown encoding: utf-8-
```

This problem is due to a mangled encoding line; apparently this must be fine on other Python implementations, but still best to fix:

```python
# -*- coding: utf-8-*-
```

```
======================================================================
FAIL: tests.test_middlewares.TestRequestTimeMiddleware.test_log_get_request
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Users/jbaker/opensource/falcon/tests/test_middlewares.py", line 116, in test_log_get_request
    self.assertTrue(context['mid_time'] > context['start_time'],
  File "/Users/jbaker/jythondev/jython27/dist/Lib/site-packages/unittest2/case.py", line 678, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : process_resource not executed after request
```

This test is relying on the compared timestamps of having a higher precision than ms, which is not available on Java. Patch:

```diff
diff --git a/tests/test_middlewares.py b/tests/test_middlewares.py
index 9c37e34..5be6b21 100644
--- a/tests/test_middlewares.py
+++ b/tests/test_middlewares.py
@@ -112,9 +112,9 @@ class TestRequestTimeMiddleware(TestMiddleware):
         self.assertIn("start_time", context)
         self.assertIn("mid_time", context)
         self.assertIn("end_time", context)
-        self.assertTrue(context['mid_time'] > context['start_time'],
+        self.assertTrue(context['mid_time'] >= context['start_time'],
                         "process_resource not executed after request")
-        self.assertTrue(context['end_time'] > context['start_time'],
+        self.assertTrue(context['end_time'] >= context['start_time'],
                         "process_response not executed after request")
```

Lastly, although it's not directly failing, there's no current support for coverage in Jython, since it currently uses CPython bytecode implementation details that Jython does not (yet) mimic.

**Comment by kgriffs** [comment]
Thanks! I'd love to get Falcon working on Jython for the next release.

**Comment by csojinb** [comment]
I can take a stab at this
