### ISSUE TITLE
working backwards from images.py example

### ISSUE THREAD

**Issue by BardiaAfshin** [falconry/falcon#579]
Hi there, I'm working backwards on images.py example from 
http://falcon.readthedocs.org/en/latest/user/tutorial.html#creating-resources

and I'm writting my own REST resource

POST http://uri/message/ -- to create a message
GET http://uri/message/{id} -- to retreive a message. Here's my code

app.py
```python
import falcon
import messages

#POST /message
#params
# subject
# body
#return message id

#GET /message/{id}
#return message status



api = falcon.API()

message_collection = messages.MessageCollection
message = messages.Message

api.add_route('/message', message_collection())
api.add_route('/message/{id}', message)
```

messages.py
```python
import json

class MessageCollection(object):
    def on_post(self, req, resp):
        """Handles POST requests"""
        quote = {
            'response' : 'success'
        }

        resp.body = json.dumps(quote)

class Message(object):
    def on_get(self, req, resp, id):
        """Handles GET requests"""
        quote = {
            'status' : 'queued'
        }

        resp.body = json.dumps(quote)
```

I'm getting this error when I run gunicorn and make a request to http://localhost:8000/messages/123
```log
[2015-08-03 10:25:17 -0700] [25151] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/bafshin/workspace/expeditions/falcon-spike/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/bafshin/workspace/expeditions/falcon-spike/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/bafshin/workspace/expeditions/falcon-spike/venv/lib/python2.7/site-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
TypeError: unbound method on_get() must be called with Message instance as first argument (got Request instance instead)
```

When I google, there's no apparent distinct result of what's going on, allot of the results on top poing to the WSGI module, and that's shared across more frameworks than just Falcon. Help?

**Comment by swizzard** [comment]
This is your problem:

	api.add_route('/message/{id}', message)
	
You have to instantiate the classes before passing them to `add_route`:

	api.add_route('/message/{id}', messages.Message())
	
(You also don't have to assign them to temporary variables.)

**Comment by BardiaAfshin** [comment]
wow. thanks. you nailed the problem.
