### ISSUE TITLE
errors.HTTPInvalidParam(msg, name) when using dictionary in simulate_get

### ISSUE THREAD

**Issue by arindamchoudhury** [falconry/falcon#997]
Hi,

```python
def test_info(self):
        payload = {
            'config': json.dumps({
                'a': 1,
                #'b':2,
            }),
            'info': json.dumps({
                'x': 1,
                #'y': 2,
            })
        }

        result = self.simulate_get('/v1/info', params=payload)
        self.assertEqual(result.status_code, 200)
```
this works. But, 

```python
def test_info(self):
        payload = {
            'config': json.dumps({
                'a': 1,
                'b':2,
            }),
            'info': json.dumps({
                'x': 1,
                'y': 2,
            })
        }

        result = self.simulate_get('/v1/info', params=payload)
        self.assertEqual(result.status_code, 200)
```

this gives following error:
```bash
Traceback (most recent call last):
  File "/home/arindam/goproj/src/github.com/test/demo/resources/info.py", line 10, in on_get
    config = req.get_param_as_dict('config')
  File "/usr/lib/python2.7/site-packages/falcon/request.py", line 1162, in get_param_as_dict
    raise errors.HTTPInvalidParam(msg, name)
HTTPInvalidParam
```

demo code is available here: [https://github.com/arindamchoudhury/demo.git](url)
 Thanks,
Arindam Choudhury

**Comment by kornicameister** [comment]
@arindamchoudhury, tested this with **falcon==1.1.0** using your demo 

```sh
(demo) ✔  ~/dev/falcon-tests/demo [master {origin/master}|✚ 6…1] 
07:58 $ nosetests tests/ --verbose
test_info (demo.tests.test.TestAccount) ... 2017-02-23T07:58:58 - demo.resources.info - INFO - None
2017-02-23T07:58:58 - demo.resources.info - INFO - None
ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

what version of falcon did you use ?

**Comment by vytas7** [comment]
Hi @arindamchoudhury !
I'm going to close this in the absence of further information, but do not hesitate to retest your example with Falcon 2.0, and reopen if needed!
